# Generated by Django 3.2.6 on 2021-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='cover.jpg', upload_to=''),
        ),
    ]
